### ISSUE TITLE
How does this integrate with Current Thermostat?

### ISSUE THREAD

**Issue by Chris2fourlaw** [Willseph/RaspberryPiThermostat#3]
In the pictures, you show the existing thermostat connected. Will the RasPi be able to see if the Thermostat is on or what temperature vise versa? I know that this is an old project, but I hope you'll be able to answer this.

**Comment by Willseph** [comment]
The Raspberry Pi (controlling the relay module) essentially overrides the existing thermostat. In reality there is no reason to keep the original thermostat's faceplate on while the Raspberry Pi is connected, other than the temperature being displayed.

The Pi doesn't "read" anything from the original thermostat; both the original faceplate and the Pi basically complete circuits within the HVAC system in order to activate the fan/heater/cooling.

With both the original faceplate and the Pi connected simultaneously, you run the risk of conflicts occurring where the original thing is telling the HVAC to enable heating, but the Pi is trying to enable cooling. In situations like this, it depends on the circuits that are being completed by both things at the same time, if that makes sense.

In my case, while the original faceplate is connected, I have to make sure that I keep the fan switch on Auto and the compressor switch on Off. Essentially I'm just using it as a temperature reading (albeit one that may not match the Pi's) that I can glance at in my kitchen without taking out my phone.

**Comment by Chris2fourlaw** [comment]
Would you be able to control the temperature through the existing thermo and have it update on the Pi or would I have to install a Touch-Display?

**Comment by Willseph** [comment]
Theoretically possible I suppose, but that's definitely outside of the scope of this project. This project is meant mainly to use the Raspberry Pi as a standalone thermostat by itself.

**Comment by Willseph** [comment]
If you know your existing thermostat panel well enough to hack it, that would be pretty cool!

**Comment by Chris2fourlaw** [comment]
I've seen ones that uses an iPhone as a screen!

**Comment by stressdidri** [comment]
Login page does not work define('AUTH_USER', 'root');
	define('AUTH_PASSWORD', 'password');
